[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc-version = "0.8.28"
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@fraxlend/=test/invariant/modules/fraxlend/",
    "fuzzlib/=lib/fuzzlib/src/",
    "swap-router/=test/invariant/modules/v3-periphery/swapRouter/",
    "v3-core/=test/invariant/modules/v3-core/",
    "v3-periphery/=test/invariant/modules/v3-periphery/",
    "v2-core/=test/invariant/modules/uniswap-v2/v2-core/contracts/",
    "v2-periphery/=test/invariant/modules/uniswap-v2/v2-periphery/contracts/",
    "uniswap-v2/=test/invariant/modules/uniswap-v2/",
    "solidity-bytes-utils/contracts/=test/invariant/modules/fraxlend/libraries/",
    "@rari-capital/solmate=node_modules/solmate"
]